### ISSUE TITLE
Upload to maven or jcenter to enable easier setup

### ISSUE THREAD

**Issue by Franzaine** [Pixplicity/svg-android#15]
To make the library easier to setup uploading it to a repo central should be considered:
- [x] Uploaded to Maven or jCenter
- [x] The documentation updated with the new setup-method

(If it is available in one of those places already or not wished to be so I am sorry for creating this issue. Consider adding it to the Android Arsenal so it is easier to find as well)

**Comment by pflammertsma** [comment]
Yes, thanks for the suggestion. It is typically a colleague that takes care of these things, but unfortunately he's no longer at Pixplicity. I'll take a look when I have a chance.

**Comment by jjhesk** [comment]
would you do that too? many thanks

**Comment by pflammertsma** [comment]
We've added the AAR to Bintray.
