### ISSUE TITLE
Upload to Maven Central (or JCenter)

### ISSUE THREAD

**Issue by rharter** [Pixplicity/svg-android#30]
This library looks great, but is there a reason this library isn't in Maven Central or JCenter?  Having to add your bintray repo and hoping that the library will always be available there is a bit of a red flag.

**Comment by pflammertsma** [comment]
You're absolutely right. We accidentally let this library slip, it should be on jCenter soon.

**Comment by pflammertsma** [comment]
The problem appears to have resurfaced for the 1.1.0 release. See issue #35.

**Comment by vlad-roid** [comment]
@pflammertsma Resurfaced again? 1.1.3 is failing even with the bintray repository added.

**Comment by sikanderrafiq** [comment]
Hi,
I have added the following dependencies 
   implementation 'com.pixplicity.sharp:library:1.1.0'

and it is synced properly, but still getting issues in import statement.

import com.pixplicity.sharp.Sharp;

and unable to use Sharp.
Any solution to this problem. I have migrated to androidx

Thanks in advance.

Regards,
Sikander
