### ISSUE TITLE
Remove needless coupling between View and SharpDrawable

### ISSUE THREAD

**Issue by jtietema** [Pixplicity/svg-android#33]
To get a `SharpDrawable` you need to pass a `View` instance for the sole purpose, that the `SharpDrawable` can "prepare" that `View`. That doesn't make much sense if you don't want to pass that `SharpDrawable` to a `View`. In my case I would like to use it to render to a `Canvas`, so now I am forced to instantiate a `View` just to satisfy the API parameters and then throw it away.

Maybe it would make more sense to "prepare" the `View` in the `Sharp#into()` method?

**Comment by pflammertsma** [comment]
I'll rethink my approach, and good points.

Note that you don't need a SharpDrawable for your canvas; I'd suggest using
a SharpPicture instead since the drawable is only really a wrapper.

**Comment by jtietema** [comment]
I see, but that means I have to make a special exception for the drawing of an SVG. It would be nice if can just draw it as any other `Drawable` 😉

**Comment by pflammertsma** [comment]
Note that you can safely provide null as the view argument for the SharpDrawable constructor.

**Comment by pflammertsma** [comment]
Resolved in 1.1.0.
