### ISSUE TITLE
 Failed to resolve: com.pixplicity.sharp:library:1.1.0

### ISSUE THREAD

**Issue by omidraha** [Pixplicity/svg-android#35]
Hi,
When I add this line:

```    compile 'com.pixplicity.sharp:library:1.1.0'```

To the `build.gradle` of `app` on the `dependencies` section, I get this error while try to sync:

``` Failed to resolve: com.pixplicity.sharp:library:1.1.0```

I don't have this problem, with other library of `pixplicity` like:

```compile 'com.pixplicity.multiviewpager:library:1.0'```

More details:

File: `build.gradle` (App)
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
File: `build.gradle` (app)
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

    defaultConfig {
        applicationId "org.sample.app"
        minSdkVersion 17
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.pixplicity.multiviewpager:library:1.0'
    compile 'com.android.support:appcompat-v7:25.3.0'
    compile 'com.android.support:design:25.3.0'
    compile 'com.github.manuelpeinado.imagelayout:imagelayout:1.1.0'
    compile 'com.github.chrisbanes.photoview:library:1.2.3'
    compile 'com.pixplicity.sharp:library:1.1.0'
}

```
Thanks.

**Comment by andreibalmos** [comment]
The library is not yet uploaded to Maven or JCenter. 
There is already a bug for that: https://github.com/Pixplicity/sharp/issues/30

Meanwhile add the bintray repo to repositories in build.gradle (app level)
```
repositories {
    mavenCentral()
    jcenter()
    maven {
        url  "http://dl.bintray.com/pixplicity/android"
    }
}
```

**Comment by pflammertsma** [comment]
Seems something went wrong with the Maven Central submission. I've requested it again and expect 1.1.0 to be available on Maven Central and JCenter later in the day.

In the meantime, @andreibalmos workaround will alleviate the problem.

**Comment by pflammertsma** [comment]
1.1.0 should be on JCenter now. Can you confirm the problem is resolved on your end?

**Comment by omidraha** [comment]
Thanks, now `jcenter` repository  (my above configs) works with `1.1.0`.
