### ISSUE TITLE
SVG rendered with dashes instead of solid line

### ISSUE THREAD

**Issue by camilamiranda** [Pixplicity/svg-android#56]
I'm trying to display an SVG, but it's showing up with dashed lines instead of solid ones
Here's the link to the svg
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjt25aA9sTmAhUpTd8KHcJ6A98QjRx6BAgBEAQ&url=https%3A%2F%2Ffr.wikipedia.org%2Fwiki%2FFichier%3AMus%25C3%25A9e_de_Chemtou_-_plan.svg&psig=AOvVaw35rtLbWkSaIQ7uPlazjckL&ust=1576955186223429

**Comment by vlad-roid** [comment]
Sorry, my bad, should be fixed as soon as the pull request is merged!
