### ISSUE TITLE
Incompatible with android studio 4

### ISSUE THREAD

**Issue by VonLisboa** [Pixplicity/svg-android#59]
Incompatible with android studio 4
<pre>gradle-wrapper.properties: distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
dependencies {
    classpath 'com.android.tools.build:gradle:4.0.1'
}
</pre>
I had to downgrade the version, as bellow:
<pre>gradle-wrapper.properties: distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
dependencies {
    classpath 'com.android.tools.build:gradle:3.6.0'
}
</pre>
the easiest solution for now...

**Comment by longnguyen0410** [comment]
I have same issue
