### ISSUE TITLE
Moving from JCenter to MavenCentral

### ISSUE THREAD

**Issue by lebzuch** [Pixplicity/svg-android#61]
Hey! Any plans to migrate to MavenCentral as [JCenter will be sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) on May 1st, 2021?

Useful hints on the migration process can be found [here](https://chris.banes.dev/publishing-to-maven-central/).

Thanks!

**Comment by lebzuch** [comment]
Hey! I saw that there was a commit for moving from bintray to mavencentral https://github.com/Pixplicity/sharp/commit/fcb4c01f8aa7ab5634cde48528a29ce3533a418d but my IDE shows that there is no version 1.1.3 available: `Could not resolve com.pixplicity.sharp:library:1.1.3@aar`
When I can expect this release?

Best,
Krzysiek

**Comment by ghost** [comment]
i experienced the same thing, @lebzuch 

I hope it will be available in maven soon

**Comment by AnonymousWalker** [comment]
also same for me, waiting for it published to maven repo

**Comment by MarkCupitt** [comment]
Also cannot find it, mavenCentral still points to JCenter

```
Could not GET 'http://dl.bintray.com/pixplicity/android/com/pixplicity/sharp/library/1.0.2/library-1.0.2.pom'. Received status code 403 from server: Forbidden
```

**Comment by milkrun** [comment]
Just wondering out loud: Can we put this in MavenCentral ourselves?

**Comment by jcamarena-sh** [comment]
Also same for me, tried to download from mavenCentral() but not get the repo. Is there any version available on mavenCentral? Thanks in advance

**Comment by yersonrr** [comment]
Hi, I was looking for the package in MavenCentral. Is it possible to publish it?

**Comment by mlagerberg** [comment]
Hi all, the most recent version should now be available on mavenCentral:

```
<dependency>
  <groupId>com.pixplicity.sharp</groupId>
  <artifactId>sharp</artifactId>
  <version>1.1.3</version>
  <type>aar</type>
</dependency>
```

**Comment by milkrun** [comment]
When I use this, I get "failed to resolve"

    implementation 'com.pixplicity.sharp:library:1.1.3@aar'

**Comment by milkrun** [comment]
Nevermind, here is the correct incantation -- the README needs to be updated

	implementation "com.pixplicity.sharp:sharp:1.1.3@aar"

**Comment by jcamarena-sh** [comment]
It works to me! Thanks @mlagerberg
